# Logistic Regression Neural Network

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

In [2]:
# array1 = np.array([np.nan, 1, 2])

# nan_array = np.isnan(array1)
# not_nan_array = ~ nan_array
# array2 = array1[not_nan_array]

# np.count_nonzero(np.isnan(array1))
# np.count_nonzero(~np.isnan(array1))

In [3]:
import pandas as pd

In [4]:
import scipy
from PIL import Image
from scipy import ndimage
%matplotlib inline

In [5]:
import numpy as np
import gdal
import os
import pandas as pd
import geopandas as gpd
from skimage import io
from PIL import Image
from skimage.io import imread
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
# reading the training data

data = pd.read_csv("C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\train.csv")
data.drop(data.columns[0], axis = 1, inplace = True)
data

,Image6band5,Image6band4,Image6band3,Image6band2,Image6band1,Image5band5,Image5band4,Image5band3,Image5band2,Image5band1,...,Image2band4,Image2band3,Image2band2,Image2band1,Image1band5,Image1band4,Image1band3,Image1band2,Image1band1,class
0,3426.0,869.0,573.5,874.0,979.5,4224.0,939.0,580.0,968.0,1103.0,...,1565.5,1520.5,1401.5,1480.5,3063.0,1487.0,973.0,1209,1208.0,1
1,3304.0,937.5,600.5,888.5,1003.0,4176.0,909.0,579.0,945.0,1088.0,...,1203.0,1115.0,1068.0,1247.5,3081.0,1494.0,945.0,1195,1191.0,1
2,3096.0,891.5,595.5,876.0,990.5,4029.0,918.0,574.0,953.0,1107.0,...,1365.5,1292.0,1190.5,1341.5,3443.0,1591.0,974.0,1258,1216.0,1
3,3634.0,929.5,574.0,917.5,1007.0,3305.0,934.0,588.0,989.0,1095.0,...,1616.0,1618.0,1546.0,1501.0,2838.0,1316.0,874.0,1120,1175.0,1
4,3329.5,846.5,560.5,866.5,985.0,4186.0,939.0,580.0,968.0,1109.0,...,1554.5,1535.0,1425.0,1508.5,3392.0,1614.0,989.0,1243,1197.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,2019.5,1378.0,1242.5,1262.0,1328.0,3460.0,1340.0,673.0,1157.0,1202.0,...,1144.5,1125.0,1105.0,1289.0,2825.0,1560.0,1081.0,1218,1221.0,2
157,3102.5,1002.5,691.0,970.5,1079.5,2549.0,1203.5,880.5,1171.0,1262.5,...,1915.5,1900.5,1699.0,1593.0,2650.0,1917.0,1675.0,1574,1559.0,2
158,2529.0,1846.5,1792.5,1502.5,1420.5,2352.0,1599.0,1427.0,1375.0,1424.0,...,1893.0,1785.5,1522.5,1482.5,2681.0,2044.0,1840.0,1676,1575.0,2
159,2071.0,1186.0,936.5,1025.5,1161.0,2087.0,1192.5,974.5,1090.0,1264.5,...,1443.0,1211.5,1168.0,1322.5,2481.0,1449.0,1180.0,1296,1350.0,2
160,2011.5,1218.5,1024.0,1077.5,1150.0,4280.0,1162.5,673.5,1105.0,1195.5,...,1284.5,1211.0,1212.0,1344.0,2736.0,1769.0,1680.0,1527,1506.0,2

In [7]:
train = data.to_numpy()
train

array([[3.4260e+03, 8.6900e+02, 5.7350e+02, ..., 1.2090e+03, 1.2080e+03,
        1.0000e+00],
       [3.3040e+03, 9.3750e+02, 6.0050e+02, ..., 1.1950e+03, 1.1910e+03,
        1.0000e+00],
       [3.0960e+03, 8.9150e+02, 5.9550e+02, ..., 1.2580e+03, 1.2160e+03,
        1.0000e+00],
       ...,
       [2.5290e+03, 1.8465e+03, 1.7925e+03, ..., 1.6760e+03, 1.5750e+03,
        2.0000e+00],
       [2.0710e+03, 1.1860e+03, 9.3650e+02, ..., 1.2960e+03, 1.3500e+03,
        2.0000e+00],
       [2.0115e+03, 1.2185e+03, 1.0240e+03, ..., 1.5270e+03, 1.5060e+03,
        2.0000e+00]])

In [8]:
# some useful commands for numpy array

# np.max(train)

# np.where(train == np.max(train))
# train[40, 16]

# np.count_nonzero(np.isnan(train))

In [9]:
train.shape

(161, 31)

# splitting the train data in train and cross validation in 80-20 ratio

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split

# # creating matrix
# input_matrix = np.arange(46928*28*28).reshape((46928,28,28))
# print('Input shape: ', input_matrix.shape)
# # splitting into two matrices of second matrix by size
# second_size = 5000/46928

# X1, X2 = train_test_split(input_matrix, test_size=second_size)

# print('X1 shape: ', X1.shape)
# print('X2 shape: ', X2.shape)

# output:::
            
# Input shape:  (46928, 28, 28)
# X1 shape:  (41928, 28, 28)
# X2 shape:  (5000, 28, 28)

In [11]:
cv_size = 20/80

train_1, cv = train_test_split(train, test_size = cv_size)

In [12]:
train_x = train_1[:, :30]
train_y = train_1[:, 30:]

cv_x = cv[:, :30]
cv_y = cv[:, 30:]

train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((120, 30), (120, 1), (41, 30), (41, 1))

In [13]:
train_y = train_y.astype("int")
cv_y = cv_y.astype("int")

In [14]:
train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((120, 30), (120, 1), (41, 30), (41, 1))

In [15]:
train_x = train_x.T
train_y = train_y.T

cv_x = cv_x.T
cv_y = cv_y.T

train_x.shape, train_y.shape, cv_x.shape, cv_y.shape

((30, 120), (1, 120), (30, 41), (1, 41))

# for logistic Regression we have output as 0 and 1, but we have 1 and 2, so replacing 1 with 0 and 2 with 1

In [16]:
cv_y[cv_y[:] == 1] = 0

In [17]:
cv_y[cv_y[:] == 2] = 1

In [18]:
train_y[train_y[:] == 1] = 0

In [19]:
train_y[train_y[:] == 2] = 1

# preparing the test data

In [20]:
# setting up the test data
# for refer tp separate fiel
# in this file read all the images, split the images individual image in single band image, convert them into numpu array
# create a dataframe reading all the pixels values expect those of the training(161) and concat them
# for the test dataframe will have (5 x ((8963*8298)-161))

In [21]:
# taking a sample of the testdata and seeing that does it perform, accordingly
# testing on the indices (3320:4150, 3588:4485) of all images and all bands.

In [22]:
# reading the csv file which has the labeled indices..

labeled_indices = pd.read_csv("C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\labeled_index.csv")

labeled_indices.drop(labeled_indices.columns[0], axis = 1, inplace = True)

In [23]:
img = ["C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\1.tif",
      "C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\2.tif",
      "C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\3.tif",
      "C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\4.tif",
      "C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\5.tif",
      "C:\\Users\\Lenovo\\Desktop\\Harvesting_Unsupervised\\6.tif"]

In [24]:
sample_test = np.zeros((830*897, 1))
sample_test.shape

(744510, 1)

In [25]:
for i in img:
    image = gdal.Open(i)
    print(image)
    
    image_zero = np.zeros((image.RasterYSize, image.RasterXSize, image.RasterCount))
    
    for b in range(image_zero.shape[2]):
        image_zero[:, :, b] = image.GetRasterBand(b + 1).ReadAsArray()
        
        for a in range(len(labeled_indices["x_index"].values)):
            image_zero[:,:,b].T[labeled_indices.iloc[a,0], labeled_indices.iloc[a,1]] = 0
            
        sample = image_zero[:,:,b].T[3320:4150, 3588:4485]
        print(sample.shape)
        sample = sample.reshape((830*897, 1))
        print(sample.shape)
        
        sample_test = np.concatenate((sample, sample_test), axis = 1)
        
sample_test

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F08D0> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F0A20> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F0AE0> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F09C0> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F0AE0> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x000001CC257F09C0> >
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)
(830, 897)
(744510, 1)

array([[3808.5, 1182. ,  737.5, ..., 1225. , 1277. ,    0. ],
       [3775.5, 1182. ,  719.5, ..., 1216. , 1289. ,    0. ],
       [3742.5, 1144.5,  720. , ..., 1212. , 1284. ,    0. ],
       ...,
       [2402. , 1145. ,  868.5, ..., 1135. , 1242. ,    0. ],
       [2226. , 1145. ,  839.5, ..., 1119. , 1245. ,    0. ],
       [2412.5, 1182. ,  874. , ..., 1129. , 1255. ,    0. ]])

In [26]:
sample_test.shape

(744510, 31)

In [27]:
sample_test_df = pd.DataFrame(data = sample_test)
sample_test_df

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,3808.5,1182.0,737.5,1048.0,1082.5,4148.0,945.0,663.5,1023.5,1196.0,...,1541.0,1468.5,1349.5,1406.0,3430.0,1359.0,924.0,1225.0,1277.0,0.0
1,3775.5,1182.0,719.5,1052.0,1088.0,4092.5,945.0,655.0,1020.5,1193.0,...,1541.0,1462.5,1351.0,1403.0,3459.0,1359.0,915.0,1216.0,1289.0,0.0
2,3742.5,1144.5,720.0,1050.5,1090.5,4083.5,972.5,654.0,1024.5,1182.0,...,1551.0,1463.5,1359.0,1405.0,3435.0,1358.0,913.0,1212.0,1284.0,0.0
3,3763.0,1144.5,729.5,1044.5,1084.5,4086.0,972.5,648.0,1028.0,1178.5,...,1551.0,1458.5,1345.5,1405.5,3265.0,1358.0,929.0,1197.0,1269.0,0.0
4,3565.0,996.0,704.0,997.0,1080.0,4042.5,955.0,661.0,1030.0,1181.5,...,1547.0,1485.5,1339.0,1385.0,3102.0,1341.0,958.0,1201.0,1282.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744505,2497.5,1192.5,911.0,1093.0,1168.5,1847.5,1254.5,1123.5,1190.0,1357.0,...,1160.0,1022.0,1074.5,1256.5,2268.0,1254.0,1001.0,1135.0,1268.0,0.0
744506,2534.5,1192.5,893.5,1089.5,1177.5,1860.0,1254.5,1141.5,1196.0,1362.0,...,1160.0,974.0,1077.0,1243.5,2260.0,1254.0,1020.0,1154.0,1264.0,0.0
744507,2402.0,1145.0,868.5,1069.5,1147.5,1738.0,1218.0,1111.5,1165.5,1350.5,...,1135.5,971.0,1043.5,1229.0,2268.0,1207.0,952.0,1135.0,1242.0,0.0
744508,2226.0,1145.0,839.5,1019.0,1127.0,1678.5,1218.0,1008.0,1120.0,1321.5,...,1135.5,917.0,1032.0,1217.5,2404.0,1207.0,916.0,1119.0,1245.0,0.0
744509,2412.5,1182.0,874.0,1062.0,1158.0,1898.0,1211.5,1034.0,1143.0,1331.5,...,1179.0,958.0,1049.5,1212.5,2458.0,1197.0,934.0,1129.0,1255.0,0.0

In [28]:
sample_test_df.drop(sample_test_df.columns[30], axis = 1, inplace = True)
sample_test_df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,3808.5,1182.0,737.5,1048.0,1082.5,4148.0,945.0,663.5,1023.5,1196.0,...,2057.0,1541.0,1468.5,1349.5,1406.0,3430.0,1359.0,924.0,1225.0,1277.0
1,3775.5,1182.0,719.5,1052.0,1088.0,4092.5,945.0,655.0,1020.5,1193.0,...,2106.5,1541.0,1462.5,1351.0,1403.0,3459.0,1359.0,915.0,1216.0,1289.0
2,3742.5,1144.5,720.0,1050.5,1090.5,4083.5,972.5,654.0,1024.5,1182.0,...,2128.0,1551.0,1463.5,1359.0,1405.0,3435.0,1358.0,913.0,1212.0,1284.0
3,3763.0,1144.5,729.5,1044.5,1084.5,4086.0,972.5,648.0,1028.0,1178.5,...,2137.5,1551.0,1458.5,1345.5,1405.5,3265.0,1358.0,929.0,1197.0,1269.0
4,3565.0,996.0,704.0,997.0,1080.0,4042.5,955.0,661.0,1030.0,1181.5,...,2133.5,1547.0,1485.5,1339.0,1385.0,3102.0,1341.0,958.0,1201.0,1282.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744505,2497.5,1192.5,911.0,1093.0,1168.5,1847.5,1254.5,1123.5,1190.0,1357.0,...,2109.0,1160.0,1022.0,1074.5,1256.5,2268.0,1254.0,1001.0,1135.0,1268.0
744506,2534.5,1192.5,893.5,1089.5,1177.5,1860.0,1254.5,1141.5,1196.0,1362.0,...,2118.0,1160.0,974.0,1077.0,1243.5,2260.0,1254.0,1020.0,1154.0,1264.0
744507,2402.0,1145.0,868.5,1069.5,1147.5,1738.0,1218.0,1111.5,1165.5,1350.5,...,2110.5,1135.5,971.0,1043.5,1229.0,2268.0,1207.0,952.0,1135.0,1242.0
744508,2226.0,1145.0,839.5,1019.0,1127.0,1678.5,1218.0,1008.0,1120.0,1321.5,...,1978.5,1135.5,917.0,1032.0,1217.5,2404.0,1207.0,916.0,1119.0,1245.0
744509,2412.5,1182.0,874.0,1062.0,1158.0,1898.0,1211.5,1034.0,1143.0,1331.5,...,2201.0,1179.0,958.0,1049.5,1212.5,2458.0,1197.0,934.0,1129.0,1255.0

In [29]:
test = sample_test_df.T
test

,0,1,2,3,4,5,6,7,8,9,...,744500,744501,744502,744503,744504,744505,744506,744507,744508,744509
0,3808.5,3775.5,3742.5,3763.0,3565.0,3452.0,3582.0,3546.5,3512.0,3454.0,...,2224.5,2266.0,2231.5,2321.5,2350.0,2497.5,2534.5,2402.0,2226.0,2412.5
1,1182.0,1182.0,1144.5,1144.5,996.0,996.0,880.0,880.0,854.0,854.0,...,1422.5,1413.0,1413.0,1290.0,1290.0,1192.5,1192.5,1145.0,1145.0,1182.0
2,737.5,719.5,720.0,729.5,704.0,631.0,590.5,586.0,579.0,580.5,...,1272.0,1294.0,1225.0,1131.0,949.5,911.0,893.5,868.5,839.5,874.0
3,1048.0,1052.0,1050.5,1044.5,997.0,928.5,909.0,914.0,907.0,902.5,...,1233.5,1242.5,1221.5,1186.0,1105.5,1093.0,1089.5,1069.5,1019.0,1062.0
4,1082.5,1088.0,1090.5,1084.5,1080.0,1062.0,1054.5,1057.0,1048.5,1045.5,...,1292.5,1291.0,1268.5,1242.0,1174.5,1168.5,1177.5,1147.5,1127.0,1158.0
5,4148.0,4092.5,4083.5,4086.0,4042.5,3707.0,3642.5,3691.5,3624.0,3511.5,...,1920.5,1972.5,1889.5,1857.5,1792.5,1847.5,1860.0,1738.0,1678.5,1898.0
6,945.0,945.0,972.5,972.5,955.0,955.0,927.5,927.5,913.0,913.0,...,1403.0,1410.5,1410.5,1317.0,1317.0,1254.5,1254.5,1218.0,1218.0,1211.5
7,663.5,655.0,654.0,648.0,661.0,694.5,650.0,644.0,639.5,633.0,...,1261.0,1322.0,1288.5,1249.0,1169.0,1123.5,1141.5,1111.5,1008.0,1034.0
8,1023.5,1020.5,1024.5,1028.0,1030.0,1041.5,1020.5,1016.5,1000.5,997.5,...,1225.5,1259.5,1244.0,1228.5,1199.0,1190.0,1196.0,1165.5,1120.0,1143.0
9,1196.0,1193.0,1182.0,1178.5,1181.5,1206.0,1190.5,1164.5,1175.5,1179.0,...,1400.0,1412.0,1412.0,1395.0,1382.0,1357.0,1362.0,1350.5,1321.5,1331.5
10,3250.5,3245.0,3211.0,3251.0,3195.0,2519.5,2153.5,2122.0,2103.0,2053.5,...,1650.5,1781.0,1708.5,1620.0,1463.0,1563.0,1635.5,1517.0,1512.5,1804.0
11,875.0,875.0,886.0,886.0,917.0,917.0,922.0,922.0,907.0,907.0,...,1272.5,1299.0,1299.0,1180.5,1180.5,1126.5,1126.5,1091.0,1091.0,1073.0
12,582.5,576.0,575.5,566.0,594.0,677.5,675.5,673.0,667.5,668.5,...,1112.5,1177.0,1184.5,1144.5,1011.5,978.0,1029.0,965.5,838.0,972.0
13,934.0,924.0,929.5,921.5,942.5,980.5,957.5,957.0,959.5,961.0,...,1096.0,1132.0,1139.5,1107.5,1050.0,1020.5,1036.5,1004.0,943.5,1032.0
14,1097.5,1100.0,1098.5,1090.5,1100.0,1149.5,1119.5,1134.0,1122.0,1129.5,...,1259.0,1276.5,1284.5,1286.5,1212.0,1226.5,1230.0,1208.0,1176.5,1203.0
15,1897.0,1912.0,1897.0,1874.0,1895.0,1886.0,1809.0,1781.0,1785.0,1760.0,...,2109.0,2164.0,2115.0,2033.0,1954.0,2024.0,1988.0,1853.0,1990.0,2147.0
16,1541.0,1541.0,1546.0,1546.0,1559.0,1559.0,1573.0,1573.0,1562.0,1562.0,...,1387.0,1379.0,1379.0,1297.0,1297.0,1215.0,1215.0,1201.0,1201.0,1219.0
17,1437.0,1430.0,1431.0,1427.0,1438.0,1502.0,1525.0,1508.0,1524.0,1514.0,...,1214.0,1259.0,1266.0,1170.0,1120.0,1115.0,1083.0,1043.0,979.0,1081.0
18,1456.0,1440.0,1439.0,1437.0,1456.0,1487.0,1491.0,1487.0,1479.0,1482.0,...,1252.0,1268.0,1267.0,1261.0,1204.0,1220.0,1202.0,1157.0,1115.0,1198.0
19,1594.0,1618.0,1624.0,1601.0,1616.0,1628.0,1632.0,1656.0,1655.0,1673.0,...,1453.0,1470.0,1479.0,1470.0,1417.0,1421.0,1422.0,1392.0,1356.0,1397.0
20,2057.0,2106.5,2128.0,2137.5,2133.5,2105.0,2063.0,2064.5,2038.0,2014.5,...,2070.0,2166.0,2241.0,2182.5,2050.0,2109.0,2118.0,2110.5,1978.5,2201.0
21,1541.0,1541.0,1551.0,1551.0,1547.0,1547.0,1537.0,1537.0,1539.0,1539.0,...,1361.5,1310.0,1310.0,1251.0,1251.0,1160.0,1160.0,1135.5,1135.5,1179.0
22,1468.5,1462.5,1463.5,1458.5,1485.5,1471.5,1397.5,1416.0,1420.0,1427.0,...,1101.0,1141.5,1158.5,1155.5,1083.5,1022.0,974.0,971.0,917.0,958.0
23,1349.5,1351.0,1359.0,1345.5,1339.0,1314.0,1275.0,1296.5,1286.0,1296.5,...,1112.5,1123.5,1137.0,1161.0,1100.0,1074.5,1077.0,1043.5,1032.0,1049.5
24,1406.0,1403.0,1405.0,1405.5,1385.0,1376.0,1329.0,1329.5,1347.0,1335.0,...,1290.0,1297.5,1290.5,1311.0,1283.0,1256.5,1243.5,1229.0,1217.5,1212.5
25,3430.0,3459.0,3435.0,3265.0,3102.0,2954.0,2940.0,2969.0,3005.0,3036.0,...,2286.0,2371.0,2428.0,2402.0,2313.0,2268.0,2260.0,2268.0,2404.0,2458.0
26,1359.0,1359.0,1358.0,1358.0,1341.0,1341.0,1365.0,1365.0,1352.0,1352.0,...,1393.0,1383.0,1383.0,1282.0,1282.0,1254.0,1254.0,1207.0,1207.0,1197.0
27,924.0,915.0,913.0,929.0,958.0,984.0,972.0,976.0,999.0,995.0,...,1087.0,1119.0,1102.0,1058.0,1020.0,1001.0,1020.0,952.0,916.0,934.0
28,1225.0,1216.0,1212.0,1197.0,1201.0,1195.0,1182.0,1194.0,1197.0,1196.0,...,1174.0,1195.0,1191.0,1196.0,1158.0,1135.0,1154.0,1135.0,1119.0,1129.0
29,1277.0,1289.0,1284.0,1269.0,1282.0,1268.0,1261.0,1274.0,1267.0,1267.0,...,1299.0,1302.0,1292.0,1297.0,1264.0,1268.0,1264.0,1242.0,1245.0,1255.0

In [30]:
test_x = test.to_numpy()
test_x

array([[3808.5, 3775.5, 3742.5, ..., 2402. , 2226. , 2412.5],
       [1182. , 1182. , 1144.5, ..., 1145. , 1145. , 1182. ],
       [ 737.5,  719.5,  720. , ...,  868.5,  839.5,  874. ],
       ...,
       [ 924. ,  915. ,  913. , ...,  952. ,  916. ,  934. ],
       [1225. , 1216. , 1212. , ..., 1135. , 1119. , 1129. ],
       [1277. , 1289. , 1284. , ..., 1242. , 1245. , 1255. ]])

In [31]:
test_x.shape

(30, 744510)

# feature normaliztion

In [32]:
train_x.shape

(30, 120)

In [33]:
for i in range(train_x.shape[0]):
    a = np.mean(train_x[i, :])
    b = np.std(train_x[i, :])
    #print(train_x[i, :])
    #print(a," : ", b ,"\n")
    train_x[i, :] = (train_x[i, :] - a) / b
    cv_x[i, :] = (cv_x[i, :] - a) / b
    test_x[i, :] = (test_x[i, :] - a) / b

# defining functions

In [34]:
# GRADED FUNCTION: sigmoid

def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [35]:
# GRADED FUNCTION: initialize_with_zeros

def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    w = np.zeros((dim, 1))
    b = 0
    ### END CODE HERE ###

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [36]:
# GRADED FUNCTION: propagate

def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    ### START CODE HERE ### (≈ 2 lines of code)
    A = sigmoid(np.dot(w.T, X) + b)                                           # compute activation
    cost = -1 / m * np.sum(Y * np.log(A) + (1-Y) * np.log(1-A))                                 # compute cost
    ### END CODE HERE ###
    
    # BACKWARD PROPAGATION (TO FIND GRAD)
    ### START CODE HERE ### (≈ 2 lines of code)
    dw = (1/m)*np.dot(X, (A-Y).T)
    db = (1/m)*np.sum((A - Y))
    ### END CODE HERE ###

    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [37]:
# GRADED FUNCTION: optimize

def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    """
    This function optimizes w and b by running a gradient descent algorithm
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of shape (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat), of shape (1, number of examples)
    num_iterations -- number of iterations of the optimization loop
    learning_rate -- learning rate of the gradient descent update rule
    print_cost -- True to print the loss every 100 steps
    
    Returns:
    params -- dictionary containing the weights w and bias b
    grads -- dictionary containing the gradients of the weights and bias with respect to the cost function
    costs -- list of all the costs computed during the optimization, this will be used to plot the learning curve.
    
    Tips:
    You basically need to write down two steps and iterate through them:
        1) Calculate the cost and the gradient for the current parameters. Use propagate().
        2) Update the parameters using gradient descent rule for w and b.
    """
    
    costs = []
    
    for i in range(num_iterations):
        
        
        # Cost and gradient calculation (≈ 1-4 lines of code)
        ### START CODE HERE ### 
        grads, cost = propagate(w, b, X, Y)
        ### END CODE HERE ###
        
        # Retrieve derivatives from grads
        dw = grads["dw"]
        db = grads["db"]
        
        # update rule (≈ 2 lines of code)
        ### START CODE HERE ###
        w = w - learning_rate*dw
        b = b - learning_rate*db
        ### END CODE HERE ###
        
        # Record the costs
        if i % 100 == 0:
            costs.append(cost)
        
        # Print the cost every 100 training iterations
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [38]:
# GRADED FUNCTION: predict

def predict(w, b, X):
    '''
    Predict whether the label is 0 or 1 using learned logistic regression parameters (w, b)
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    
    Returns:
    Y_prediction -- a numpy array (vector) containing all predictions (0/1) for the examples in X
    '''
    
    m = X.shape[1]
    Y_prediction = np.zeros((1,m))
    w = w.reshape(X.shape[0], 1)
    
    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    ### START CODE HERE ### (≈ 1 line of code)
    A = sigmoid(np.dot(w.T, X) + b)
    ### END CODE HERE ###
    
    for i in range(A.shape[1]):
        
        # Convert probabilities A[0,i] to actual predictions p[0,i]
        ### START CODE HERE ### (≈ 4 lines of code)
        if A[0, i] > 0.5:
            Y_prediction[0, i] = 1
        else:
            Y_prediction[0, i] = 0
        ### END CODE HERE ###
    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [39]:
# GRADED FUNCTION: model

def model(X_train, Y_train, X_test, Y_test, num_iterations = 2000, learning_rate = 0.5, print_cost = False):
    """
    Builds the logistic regression model by calling the function you've implemented previously
    
    Arguments:
    X_train -- training set represented by a numpy array of shape (num_px * num_px * 3, m_train)
    Y_train -- training labels represented by a numpy array (vector) of shape (1, m_train)
    X_test -- test set represented by a numpy array of shape (num_px * num_px * 3, m_test)
    Y_test -- test labels represented by a numpy array (vector) of shape (1, m_test)
    num_iterations -- hyperparameter representing the number of iterations to optimize the parameters
    learning_rate -- hyperparameter representing the learning rate used in the update rule of optimize()
    print_cost -- Set to true to print the cost every 100 iterations
    
    Returns:
    d -- dictionary containing information about the model.
    """
    
    ### START CODE HERE ###
    
    # initialize parameters with zeros (≈ 1 line of code)
    w, b = initialize_with_zeros(X_train.shape[0])

    # Gradient descent (≈ 1 line of code)
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    
    # Retrieve parameters w and b from dictionary "parameters"
    w = parameters["w"]
    b = parameters["b"]
    
    # Predict test/train set examples (≈ 2 lines of code)
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    ### END CODE HERE ###

    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [40]:
# d = model(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

a = model(train_x, train_y, cv_x, cv_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

Cost after iteration 0: 0.693147
Cost after iteration 100: 0.261008
Cost after iteration 200: 0.169562
Cost after iteration 300: 0.129147
Cost after iteration 400: 0.105819
Cost after iteration 500: 0.090388
Cost after iteration 600: 0.079303
Cost after iteration 700: 0.070890
Cost after iteration 800: 0.064249
Cost after iteration 900: 0.058852
Cost after iteration 1000: 0.054365
Cost after iteration 1100: 0.050566
Cost after iteration 1200: 0.047303
Cost after iteration 1300: 0.044465
Cost after iteration 1400: 0.041971
Cost after iteration 1500: 0.039760
Cost after iteration 1600: 0.037786
Cost after iteration 1700: 0.036010
Cost after iteration 1800: 0.034404
Cost after iteration 1900: 0.032943
train accuracy: 100.0 %
test accuracy: 100.0 %

In [41]:
for i in a:
    print("\n\n", i,"  :::  ", a[i])

 costs   :::   [0.6931471805599453, 0.26100790308559396, 0.16956170440933485, 0.12914726093324203, 0.10581904037575666, 0.09038752925381151, 0.07930265335504015, 0.07088964997632125, 0.06424914203263996, 0.058851924642643605, 0.05436465325775796, 0.05056597234543956, 0.047302571779323, 0.04446456194978833, 0.04197090088962292, 0.039760371045263865, 0.03778577498752145, 0.03601007792402668, 0.03440377069851706, 0.032943022197904286]


 Y_prediction_test   :::   [[1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.
  0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0.]]


 Y_prediction_train   :::   [[1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1.
  1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1.
  0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.
  1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1.
  1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1.]]


 w   :::   [[-0.58075074]
 [ 0.42787618]
 [ 0.4696828 ]
 [ 0.41870278]
 [ 0.44057837]
 [-0.30936888]
 [ 0.42235173]
 [ 0.2234685 ]
 [ 0.33368277]
 [ 0.20967666]
 [ 0.20265647]
 [ 0.36495369]
 [ 0.16634548]
 [ 0.29746472]
 [ 0.18971884]
 [ 0.02745256]
 [ 0.00080934]
 [ 0.00641328]
 [ 0.01270745]
 [ 0.01828147]
 [-0.27323342]
 [-0.31580741]
 [-0.286004  ]
 [-0.23551024]
 [-0.16834718]
 [-0.06510917]
 [ 0.08720821]
 [ 0.1616581 ]
 [ 0.0809042 ]
 [ 0.09592353]]


 b   :::   0.4902834500114212


 learning_rate   :::   0.005


 num_iterations   :::   2000

In [42]:
test_x

array([[ 1.66209572,  1.62101111,  1.57992649, ..., -0.08898035,
        -0.3080983 , -0.07590798],
       [ 0.30926541,  0.30926541,  0.11936375, ...,  0.12189577,
         0.12189577,  0.30926541],
       [-0.64834214, -0.71326803, -0.71146454, ..., -0.17582593,
        -0.28042875, -0.15598746],
       ...,
       [-0.70178224, -0.74591434, -0.75572148, ..., -0.56448235,
        -0.74101078, -0.65274656],
       [-0.18096857, -0.26035364, -0.29563589, ..., -0.9748193 ,
        -1.11594832, -1.02774269],
       [ 0.33204063,  0.44920272,  0.40038518, ..., -0.00968215,
         0.01960838,  0.11724346]])

In [43]:
np.count_nonzero(np.isnan(test_x))

0

In [44]:
test_y = predict(a["w"], a["b"], test_x)

In [45]:
test_y.shape

(1, 744510)

In [46]:
test_y.T

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

In [48]:
test_y = test_y.reshape((830,897))

In [49]:
test_y.shape

(830, 897)

In [51]:
test_y

array([[0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [58]:
x = test_y

In [59]:
x[x == 1] = 255
x

array([[  0.,   0.,   0., ..., 255., 255., 255.],
       [  0.,   0.,   0., ..., 255., 255., 255.],
       [  0.,   0.,   0., ..., 255., 255., 255.],
       ...,
       [  0.,   0.,   0., ..., 255., 255., 255.],
       [  0.,   0.,   0., ..., 255., 255., 255.],
       [  0.,   0.,   0., ..., 255., 255., 255.]])

In [60]:
x = x.astype("int")
x

array([[  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]])

In [56]:
import numpy as np
import os
import pandas as pd
from skimage import io
from skimage.io import imread

In [61]:
io.imsave("E:\\Internship_Harvesting\\Prediction\\test.jpg" ,x)

C:\Users\Lenovo\anaconda3\envs\env_1\lib\site-packages\ipykernel_launcher.py:1: UserWarning: E:\Internship_Harvesting\Prediction\test.jpg is a low contrast image
  """Entry point for launching an IPython kernel.
Lossy conversion from int32 to uint8. Range [0, 255]. Convert image to uint8 prior to saving to suppress this warning.